language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

sudo: false

before_script:
  - git clone https://github.com/octobercms/october.git
  - mkdir -p ./october/plugins/vojtasvoboda/reservations
  - mv !(october) october/plugins/vojtasvoboda/reservations
  - cd october
  - composer self-update
  - travis_retry composer install --no-interaction --prefer-source
  - cd plugins/vojtasvoboda/reservations
  - composer install

script:
  - ../../../vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - bash <(curl -s https://codecov.io/bash)
  - npm test
